"""
Project Euler Problem 12
========================

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""

import math

def factorsOfN(n):
  factors = []
  for i in range(1,int(math.sqrt(n))+1):
    if n%i==0:
      factors.append(i)
      factors.append(n//i)
  return set(factors)

def triNumAndItsFactorsWithIndex(n):
  triNum = (n*(n+1))//2
  if n%2==0: 
    # we have, 
    #     tn = n*(n+1)/2 Let n = 2r (i.e. n is even)
    # or, tn = 2*r(2*r+1)/2
    # or, tn = r*(2*r+1) so, r and 2r+1 are factors of tn 
    factors = {triNum}|factorsOfN(n+1)|factorsOfN(n//2)
  else:
    factors = factorsOfN(triNum)
  return [factors,triNum]

def triNumWithMoreThanNFactors(n):
  gen = 1
  while True:
    triNumAndItsFactors = triNumAndItsFactorsWithIndex(gen)
    if len(triNumAndItsFactors[0])>n: return triNumAndItsFactors[1]
    gen+=1

print(triNumWithMoreThanNFactors(500))